name: Build OmniTool

on:

  workflow_dispatch:
    
env:
  # Name of module and id separated by a slash
  INSTANCE: Writerside/omni_tool_instance
  # Replace HI with the ID of the instance in capital letters
  ARTIFACT: webHelpOMNI_TOOL_INSTANCE2-all.zip
  # Writerside docker image version
  DOCKER_VERSION: 232.10275
  # Add the variable below to upload Algolia indexes
  # Replace HI with the ID of the instance in capital letters
  ALGOLIA_ARTIFACT: algolia-indexes-OMNI_TOOL_INSTANCE.zip
  ALGOLIA_APP_NAME: AppName
  ALGOLIA_INDEX_NAME: indexname
  CONFIG_JSON_PRODUCT: OMNI_TOOL_INSTANCE
  CONFIG_JSON_VERSION: 1.0

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Writerside docs using Docker
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: ${{ env.INSTANCE }}
          artifact: ${{ env.ARTIFACT }}
          docker-version: ${{ env.DOCKER_VERSION }}

      - name: Upload documentation
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: |
            artifacts/${{ env.ARTIFACT }}
            artifacts/report.json
          retention-days: 7
      
      # Add the step below to upload Algolia indexes
      - name: Upload algolia-indexes
        uses: actions/upload-artifact@v3
        with:
          name: algolia-indexes
          path: artifacts/${{ env.ALGOLIA_ARTIFACT }}
          retention-days: 7